### ISSUE TITLE
A GUI for selecting applications to 'include' or 'exclude'

### ISSUE THREAD

**Issue by piyushsoni** [bilbofroggins/KarabinerKeyboard#15]
It's very important for a lot of users to have application specific complex shortcuts. Karabiner Elements kind of has a UI way to find the bundle identifier for an app (Event Viewer -> Frontmost Application) but it doesn't utilize it properly. An ideal GUI for creating complex modifications would have an option to select applications (for example by clicking on their open window) for both including and excluding, and then asking for the source and target keyboard combination. Please add it 🙏 Thanks!

**Comment by bilbofroggins** [comment]
@piyushsoni merged a version 0.0.8 to include app specific keybindings. Let me know if it covers your cases
