### ISSUE TITLE
The app does not work in MacOS 14.6.1

### ISSUE THREAD

**Issue by andkirby** [bilbofroggins/KarabinerKeyboard#32]
Downloaded latest the `.app` file ([0.1.1](https://github.com/bilbofroggins/KarabinerKeyboard/releases/tag/0.1.1)) and nothing happened after launching it.

Hardware: M1 2021

Please let me know if you need logs or something else.

**Comment by bilbofroggins** [comment]
Thank you! Sorry about that, pushed a fix:
[0.1.3](https://github.com/bilbofroggins/KarabinerKeyboard/releases/tag/0.1.3)

**Comment by bilbofroggins** [comment]
@andkirby I'm going to close this - I think the new version should launch. Feel free to reopen if you're still having issues
